#!/bin/sh
# File generated by ocamlbuild

cd '/Users/ossama_mady/Documents/McGill/SemesterSix/COMP520/Week 2/MiniLang/_build'

rm -f error.cmi
rm -f error.cmo
rm -f error.cmx
rm -f error.ml.depends
rm -f error.o
rm -f lexer.cmi
rm -f lexer.cmo
rm -f lexer.cmx
rm -f lexer.ml
rm -f lexer.ml.depends
rm -f lexer.o
rm -f mini.cmi
rm -f mini.cmo
rm -f mini.cmx
rm -f mini.ml.depends
rm -f mini.o
rm -f parser.cmi
rm -f parser.cmx
rm -f parser.ml
rm -f parser.ml.depends
rm -f parser.mli
rm -f parser.mli.depends
rm -f parser.o
# Also clean the script itself
rm -f '/Users/ossama_mady/Documents/McGill/SemesterSix/COMP520/Week 2/MiniLang/_build/_build/sanitize.sh'
